version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    environment:
      POSTGRES_PASSWORD: <%= ENV.fetch("db_password") %>
